services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE:-js-fastify-blog}:latest
    working_dir: /app
    command: make test
    volumes:
      - ./app:/app
